In [73]:
#Loading data
import pandas as pd

df_train = pd.read_csv("../Dataset/UNSW_NB15_training-set.csv")
df_test = pd.read_csv("../Dataset/UNSW_NB15_testing-set.csv")
df_all = pd.concat([df_train, df_test], ignore_index=True)

#Learning about the data
print(df_train)
print(df_test)
print(df_all)

            id       dur proto service state  spkts  dpkts  sbytes  dbytes  \
0            1  0.121478   tcp       -   FIN      6      4     258     172   
1            2  0.649902   tcp       -   FIN     14     38     734   42014   
2            3  1.623129   tcp       -   FIN      8     16     364   13186   
3            4  1.681642   tcp     ftp   FIN     12     12     628     770   
4            5  0.449454   tcp       -   FIN     10      6     534     268   
...        ...       ...   ...     ...   ...    ...    ...     ...     ...   
175336  175337  0.000009   udp     dns   INT      2      0     114       0   
175337  175338  0.505762   tcp       -   FIN     10      8     620     354   
175338  175339  0.000009   udp     dns   INT      2      0     114       0   
175339  175340  0.000009   udp     dns   INT      2      0     114       0   
175340  175341  0.000009   udp     dns   INT      2      0     114       0   

                 rate  ...  ct_src_dport_ltm  ct_dst_sport_ltm 

In [74]:
#Learning about categorical features
import numpy as np
columns_train = df_train.columns
for column in columns_train:
    if(type(df_train[column][0]) == type("")):
        print(column)
        unique_values_train = df_train[column].unique()
        unique_values_test = df_test[column].unique()
        print(np.sort(unique_values_train))
        print(np.sort(unique_values_test))
        print("DIFF TRAIN WITH TEST:")
        diff_arr1 = np.setdiff1d(unique_values_train, unique_values_test)
        print(diff_arr1)
        print("DIFF TEST WITH TRAIN:")
        diff_arr2 = np.setdiff1d(unique_values_test, unique_values_train)
        print(diff_arr2)
        print("######")

proto
['3pc' 'a/n' 'aes-sp3-d' 'any' 'argus' 'aris' 'arp' 'ax.25' 'bbn-rcc'
 'bna' 'br-sat-mon' 'cbt' 'cftp' 'chaos' 'compaq-peer' 'cphb' 'cpnx'
 'crtp' 'crudp' 'dcn' 'ddp' 'ddx' 'dgp' 'egp' 'eigrp' 'emcon' 'encap'
 'etherip' 'fc' 'fire' 'ggp' 'gmtp' 'gre' 'hmp' 'i-nlsp' 'iatp' 'ib'
 'icmp' 'idpr' 'idpr-cmtp' 'idrp' 'ifmp' 'igmp' 'igp' 'il' 'ip' 'ipcomp'
 'ipcv' 'ipip' 'iplt' 'ipnip' 'ippc' 'ipv6' 'ipv6-frag' 'ipv6-no'
 'ipv6-opts' 'ipv6-route' 'ipx-n-ip' 'irtp' 'isis' 'iso-ip' 'iso-tp4'
 'kryptolan' 'l2tp' 'larp' 'leaf-1' 'leaf-2' 'merit-inp' 'mfe-nsp' 'mhrp'
 'micp' 'mobile' 'mtp' 'mux' 'narp' 'netblt' 'nsfnet-igp' 'nvp' 'ospf'
 'pgm' 'pim' 'pipe' 'pnni' 'pri-enc' 'prm' 'ptp' 'pup' 'pvp' 'qnx' 'rdp'
 'rsvp' 'rtp' 'rvd' 'sat-expak' 'sat-mon' 'sccopmce' 'scps' 'sctp' 'sdrp'
 'secure-vmtp' 'sep' 'skip' 'sm' 'smp' 'snp' 'sprite-rpc' 'sps' 'srp'
 'st2' 'stp' 'sun-nd' 'swipe' 'tcf' 'tcp' 'tlsp' 'tp++' 'trunk-1'
 'trunk-2' 'ttp' 'udp' 'unas' 'uti' 'vines' 'visa' 'vmtp' 'vrrp'
 'wb-expak' 'w

In [75]:
#Checking if data has any missing values
print("Number of missing values in total:", df_all.isnull().sum().sum())

Number of missing values in total: 0


In [76]:
#Now it's time to do preprocessings
#Fist we get rid of categorical features by assigning unique numbers to them.
columns_all = df_all.columns
for column in columns_all:
    if(type(df_all[column][0]) == type("")):
        df_all[column] = pd.factorize(df_all[column])[0]
        unique_values_all = df_all[column].unique()
        print(np.sort(unique_values_all))
        print("####")


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132]
####
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
####
[ 0  1  2  3  4  5  6  7  8  9 10]
####
[0 1 2 3 4 5 6 7 8 9]
####


In [77]:
#Second we see if features need to be scaled
for column in columns_all:
    print(column, "Max:", df_all[column].max(), "Min:", df_all[column].min())

id Max: 175341 Min: 1
dur Max: 59.999989 Min: 0.0
proto Max: 132 Min: 0
service Max: 12 Min: 0
state Max: 10 Min: 0
spkts Max: 10646 Min: 1
dpkts Max: 11018 Min: 0
sbytes Max: 14355774 Min: 24
dbytes Max: 14657531 Min: 0
rate Max: 1000000.003 Min: 0.0
sttl Max: 255 Min: 0
dttl Max: 254 Min: 0
sload Max: 5988000256.0 Min: 0.0
dload Max: 22422730.0 Min: 0.0
sloss Max: 5319 Min: 0
dloss Max: 5507 Min: 0
sinpkt Max: 84371.496 Min: 0.0
dinpkt Max: 57739.24 Min: 0.0
sjit Max: 1483830.917 Min: 0.0
djit Max: 463199.2401 Min: 0.0
swin Max: 255 Min: 0
stcpb Max: 4294958913 Min: 0
dtcpb Max: 4294881924 Min: 0
dwin Max: 255 Min: 0
tcprtt Max: 3.821465 Min: 0.0
synack Max: 3.226788 Min: 0.0
ackdat Max: 2.928778 Min: 0.0
smean Max: 1504 Min: 24
dmean Max: 1500 Min: 0
trans_depth Max: 172 Min: 0
response_body_len Max: 6558056 Min: 0
ct_srv_src Max: 63 Min: 1
ct_state_ttl Max: 6 Min: 0
ct_dst_ltm Max: 59 Min: 1
ct_src_dport_ltm Max: 59 Min: 1
ct_dst_sport_ltm Max: 46 Min: 1
ct_dst_src_ltm Max: 65 Min:

In [78]:
#As we can see, they vary a lot, so I decide to do a min-max scale on it and make their intervals [0, 1]
#except our lable and first feature witch is an id and we will remove it

df_all_scaled = df_all.apply(lambda x: (x - x.min()) / (x.max() - x.min()))
df_all_scaled[columns_all[0]] = df_all[columns_all[0]]
df_all_scaled[columns_all[-1]] = df_all[columns_all[-1]]

In [79]:
#Removing id column
df_all_scaled = df_all_scaled.drop(columns_all[0], axis=1)
print(df_all_scaled)

                 dur     proto   service  state     spkts     dpkts    sbytes  \
0       2.024634e-03  0.000000  0.000000    0.0  0.000470  0.000363  0.000016   
1       1.083170e-02  0.000000  0.000000    0.0  0.001221  0.003449  0.000049   
2       2.705215e-02  0.000000  0.000000    0.0  0.000658  0.001452  0.000024   
3       2.802737e-02  0.000000  0.083333    0.0  0.001033  0.001089  0.000042   
4       7.490901e-03  0.000000  0.000000    0.0  0.000845  0.000545  0.000036   
...              ...       ...       ...    ...       ...       ...       ...   
257668  8.333335e-08  0.007576  0.000000    0.1  0.000094  0.000000  0.000006   
257669  1.843502e-02  0.000000  0.000000    0.0  0.001785  0.000726  0.001257   
257670  0.000000e+00  0.015152  0.000000    0.1  0.000000  0.000000  0.000002   
257671  0.000000e+00  0.015152  0.000000    0.1  0.000000  0.000000  0.000002   
257672  1.500000e-07  0.007576  0.000000    0.1  0.000094  0.000000  0.000006   

          dbytes      rate 

In [80]:
#Now we check our data's balancement

cnt = 10 * [0]
for lable in df_all_scaled[columns_all[-1]]:
    cnt[lable] += 1
    
for i in range(10):
    print("#lable", i, " :", cnt[i])

#lable 0  : 93000
#lable 1  : 2329
#lable 2  : 2677
#lable 3  : 24246
#lable 4  : 1511
#lable 5  : 13987
#lable 6  : 44525
#lable 7  : 16353
#lable 8  : 174
#lable 9  : 58871


In [81]:
#As we can see lables 1, 2, 4, and 8 are very imbalance and we decide to cut them off from the dataset
#But first we need to devide our data into df_train and df_test

df_train_all = df_all_scaled.iloc[:len(df_train)]
df_test_all = df_all_scaled.iloc[len(df_train):]


In [82]:
df_train = df_train_all[df_train_all[columns_all[-1]] != 1]
df_train = df_train[df_train[columns_all[-1]]  != 2]
df_train = df_train[df_train[columns_all[-1]]  != 4]
df_train = df_train[df_train[columns_all[-1]]  != 8]

cnt = 10 * [0]
for lable in df_train[columns_all[-1]]:
    cnt[lable] += 1
    
for i in range(10):
    print("#lable", i, " :", cnt[i])
    
print("######")    
df_test = df_test_all[df_test_all[columns_all[-1]] != 1]
df_test = df_test[df_test[columns_all[-1]]  != 2]
df_test = df_test[df_test[columns_all[-1]]  != 4]
df_test = df_test[df_test[columns_all[-1]]  != 8]

cnt = 10 * [0]
for lable in df_test[columns_all[-1]]:
    cnt[lable] += 1

for i in range(10):
    print("#lable", i, " :", cnt[i])
    
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

print(df_train)
print(df_test)

#lable 0  : 56000
#lable 1  : 0
#lable 2  : 0
#lable 3  : 18184
#lable 4  : 0
#lable 5  : 10491
#lable 6  : 33393
#lable 7  : 12264
#lable 8  : 0
#lable 9  : 40000
######
#lable 0  : 37000
#lable 1  : 0
#lable 2  : 0
#lable 3  : 6062
#lable 4  : 0
#lable 5  : 3496
#lable 6  : 11132
#lable 7  : 4089
#lable 8  : 0
#lable 9  : 18871
                 dur     proto   service  state     spkts     dpkts    sbytes  \
0       2.024634e-03  0.000000  0.000000    0.0  0.000470  0.000363  0.000016   
1       1.083170e-02  0.000000  0.000000    0.0  0.001221  0.003449  0.000049   
2       2.705215e-02  0.000000  0.000000    0.0  0.000658  0.001452  0.000024   
3       2.802737e-02  0.000000  0.083333    0.0  0.001033  0.001089  0.000042   
4       7.490901e-03  0.000000  0.000000    0.0  0.000845  0.000545  0.000036   
...              ...       ...       ...    ...       ...       ...       ...   
170327  1.000000e-07  0.007576  0.500000    0.1  0.000094  0.000000  0.000006   
170328  1.500000e-07

In [83]:
#Now that our preprocessing is over, it's time to devide our train and test data
#into X_train, y_train, X_test, and y_test

X_train = df_train.filter(items = df_train.columns[:-1])
y_train = df_train.filter(items = df_train.columns[-1:])

X_test = df_test.filter(items = df_test.columns[:-1])
y_test = df_test.filter(items = df_test.columns[-1:])


In [158]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# Create a Random Forest classifier
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the Random Forest classifier on the training data
random_forest.fit(X_train, np.array([x[0] for x in np.array(y_train)]))

# Get the feature importances
feature_importances = random_forest.feature_importances_

# Sort the features by importance
sorted_feature_indices = sorted(range(len(feature_importances)), key=lambda k: feature_importances[k], reverse=True)

k = 10

# Get the selected feature indices
selected_feature_indices = sorted_feature_indices[:k]

# Print the selected feature indices
print("Selected Feature Indices:", selected_feature_indices)


Selected Feature Indices: [9, 6, 34, 35, 40, 31, 30, 26, 2, 33]


In [171]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

model = RandomForestClassifier(n_estimators=100, random_state=42)

# Create the RFE object and specify the number of features to select (n_features_to_select)
rfe = RFE(estimator=model, n_features_to_select=10)  # Select top 5 features

# Fit the RFE object to the data
rfe.fit(X_train, np.array([x[0] for x in np.array(y_train)]))

# Get the selected feature indices
selected_feature_indices = rfe.get_support(indices=True)

print(selected_feature_indices)

[ 6  7  8  9 12 26 31 33 34 40]


In [176]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X_train_selected = df_train_all[df_train_all[columns_all[-1]] != 0]
X_train_selected = X_train_selected[X_train_selected[columns_all[-1]]  != 9]
X_train_selected = X_train_selected.filter(items = df_train.columns[:-1])

y_train_selected = df_train_all[df_train_all[columns_all[-1]] != 0]
y_train_selected = y_train_selected[y_train_selected[columns_all[-1]]  != 9]
y_train_selected = y_train_selected.filter(items = df_train.columns[-1:])

# Create a Random Forest classifier
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the Random Forest classifier on the training data
random_forest.fit(X_train_selected, np.array([x[0] for x in np.array(y_train_selected)]))

# Get the feature importances
feature_importances = random_forest.feature_importances_

# Sort the features by importance
sorted_feature_indices = sorted(range(len(feature_importances)), key=lambda k: feature_importances[k], reverse=True)

k = 10

# Get the selected feature indices
selected_feature_indices2 = sorted_feature_indices[:k]

# Print the selected feature indices
print("Selected Feature Indices:", selected_feature_indices2)


Selected Feature Indices: [6, 26, 1, 40, 7, 35, 27, 30, 2, 9]


In [209]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import numpy as np


# Create a SelectKBest object with the chi2 scoring function
k_best = SelectKBest(score_func=chi2, k=10)  # Select top 5 features

# Apply feature selection to your data
X_new = k_best.fit_transform(X_train, y_train)

# Get the indices of the selected features
selected_feature_indices2 = k_best.get_support(indices=True).tolist()


print("Selected features:", selected_feature_indices2)
#0.54

Selected features: [2, 10, 19, 22, 30, 32, 33, 34, 35, 40]


In [212]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.datasets import load_iris

# Create a random forest classifier as the underlying model
rf = RandomForestClassifier(random_state=42)

# Create the SelectFromModel object, specifying the random forest model
selector = SelectFromModel(estimator=rf)

# Fit the selector to the data
selector.fit(X_train, y_train)

# Transform the data to select the important features
X_selected = selector.transform(X_train)

# Get the support mask indicating selected features
feature_mask = selector.get_support()

# Get the indices of the selected features
selected_feature_indices = [i for i, mask in enumerate(feature_mask) if mask]

# Print the selected feature indices
print("Selected feature indices:", selected_feature_indices)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/feature_selection/_from_model.py:357: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator_.fit(X, y, **fit_params)


Selected feature indices: [1, 2, 6, 7, 8, 9, 10, 12, 26, 27, 30, 31, 32, 33, 34, 35, 40]


In [221]:
def array_union(arr1, arr2):
    # Concatenate the two arrays
    combined_array = arr1 + arr2

    # Create a new empty array for the union elements
    union_array = []

    # Iterate through each element in the combined array
    for element in combined_array:
        # Check if the element is not already in the union array
        if element not in union_array:
            # Add the element to the union array
            union_array.append(element)

    return union_array
#selected_feature_indices = [6, 7, 8, 9, 12, 26, 31, 33, 34, 40]

selected_feature_indices = array_union(selected_feature_indices, selected_feature_indices2)
print(selected_feature_indices)
                           
X_train_selected = X_train.iloc[:, selected_feature_indices]
X_test_selected = X_test.iloc[:, selected_feature_indices]
print(X_train_selected)

# Create a new Random Forest classifier with weighted and selected features
weighted_random_forest = RandomForestClassifier(criterion = 'entropy',
                               n_estimators = 100,
                               class_weight='balanced',
                               n_jobs = -1)

# Fit the new Random Forest classifier on the selected features
weighted_random_forest.fit(X_train_selected, np.array([x[0] for x in np.array(y_train)]))

# Make predictions on the test data using the selected features
y_pred = weighted_random_forest.predict(X_test_selected)
y_pred_train = weighted_random_forest.predict(X_train_selected)

[1, 2, 6, 7, 8, 9, 10, 12, 26, 27, 30, 31, 32, 33, 34, 35, 40, 19, 22]
           proto   service    sbytes    dbytes      rate      sttl      dttl  \
0       0.000000  0.000000  0.000016  0.000012  0.000074  0.988235  1.000000   
1       0.000000  0.000000  0.000049  0.002866  0.000078  0.243137  0.992126   
2       0.000000  0.000000  0.000024  0.000900  0.000014  0.243137  0.992126   
3       0.000000  0.083333  0.000042  0.000053  0.000014  0.243137  0.992126   
4       0.000000  0.000000  0.000036  0.000018  0.000033  0.996078  0.992126   
...          ...       ...       ...       ...       ...       ...       ...   
170327  0.007576  0.500000  0.000006  0.000000  0.166667  0.996078  0.000000   
170328  0.007576  0.500000  0.000006  0.000000  0.111111  0.996078  0.000000   
170329  0.007576  0.500000  0.000006  0.000000  0.111111  0.996078  0.000000   
170330  0.007576  0.500000  0.000006  0.000000  0.111111  0.996078  0.000000   
170331  0.007576  0.500000  0.000006  0.000000  0

In [217]:
#Getting model results
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
accuracy_train = accuracy_score(y_train, y_pred_train)

precision = precision_score(y_test, y_pred, average = "macro")
precision_train = precision_score(y_train, y_pred_train, average = "macro")

recall = recall_score(y_test, y_pred, average = "macro")
recall_train = recall_score(y_train, y_pred_train, average = "macro")

f1 = f1_score(y_test, y_pred, average = "macro")
f1_train = f1_score(y_train, y_pred_train, average = "macro")

confusion = confusion_matrix(y_test, y_pred)
confusion_train = confusion_matrix(y_train, y_pred_train)

print("accuracy", accuracy)
print("accuracy_train", accuracy_train)
print("precision",precision)
print("precision_train",precision_train)
print("recall", recall)
print("recall_train", recall_train)
print("f1", f1)
print("f1_train", f1_train)
print("confusion", confusion)
print("confision_train", confusion_train)

accuracy 0.790154990700558
accuracy_train 0.9000481412770355
precision 0.7197328961583893
precision_train 0.8972977275503761
recall 0.7564270011872659
recall_train 0.8892184748405579
f1 0.7190470872079618
f1_train 0.8658193613269575
confusion [[28524  7683     7   725    52     9]
 [ 1021  3358     5   398  1272     8]
 [   11    52  2796   332   305     0]
 [  111   302   184  7554  2967    14]
 [   31   140    27   766  3113    12]
 [   14    36     3   354    83 18381]]
confision_train [[55588   407     2     3     0     0]
 [   39 16667     8    39  1431     0]
 [    0     0  8676    53  1762     0]
 [    1    33    44 20520 12792     3]
 [    0     1    15    76 12172     0]
 [    0     3     0    26   287 39684]]


In [222]:
#new_selected_feature_indices = array_union(selected_feature_indices2, [2, 10, 19, 22, 30, 32, 33, 34, 35, 40])
new_selected_feature_indices = [1, 2, 6, 7, 8, 9, 10, 12, 26, 27, 30, 31, 32, 33, 34, 35, 40, 19, 22]
print(new_selected_feature_indices)
new_X_train_selected = X_train.iloc[:, new_selected_feature_indices]
new_X_test_selected = X_test.iloc[:, new_selected_feature_indices]

new_X_train_stacking = new_X_train_selected.copy()
#new_X_train_stacking["RF"] = y_pred_train_RF
#new_X_train_stacking["KNN"] = y_pred_train_knn
#new_X_train_stacking["MLP"] = y_pred_train_mlp
#new_X_train_stacking = new_X_train_stacking.apply(lambda x: (x - x.min()) / (x.max() - x.min()))
print(new_X_train_stacking)

new_X_test_stacking = new_X_test_selected.copy()
#new_X_test_stacking["RF"] = y_pred_RF
#new_X_test_stacking["KNN"] = y_pred_knn
#new_X_test_stacking["MLP"] = y_pred_mlp
#new_X_test_stacking = new_X_test_stacking.apply(lambda x: (x - x.min()) / (x.max() - x.min()))
print(new_X_test_stacking)

[1, 2, 6, 7, 8, 9, 10, 12, 26, 27, 30, 31, 32, 33, 34, 35, 40, 19, 22]
           proto   service    sbytes    dbytes      rate      sttl      dttl  \
0       0.000000  0.000000  0.000016  0.000012  0.000074  0.988235  1.000000   
1       0.000000  0.000000  0.000049  0.002866  0.000078  0.243137  0.992126   
2       0.000000  0.000000  0.000024  0.000900  0.000014  0.243137  0.992126   
3       0.000000  0.083333  0.000042  0.000053  0.000014  0.243137  0.992126   
4       0.000000  0.000000  0.000036  0.000018  0.000033  0.996078  0.992126   
...          ...       ...       ...       ...       ...       ...       ...   
170327  0.007576  0.500000  0.000006  0.000000  0.166667  0.996078  0.000000   
170328  0.007576  0.500000  0.000006  0.000000  0.111111  0.996078  0.000000   
170329  0.007576  0.500000  0.000006  0.000000  0.111111  0.996078  0.000000   
170330  0.007576  0.500000  0.000006  0.000000  0.111111  0.996078  0.000000   
170331  0.007576  0.500000  0.000006  0.000000  0

In [223]:
#Now it's time to learn Random Forest on our best parameters and all of the data

new_model_RF_stacking = RandomForestClassifier(criterion = 'entropy',
                               n_estimators = 100,
                               max_depth = None,
                               class_weight='balanced',
                               n_jobs = -1)
new_model_RF_stacking.fit(new_X_train_stacking, np.array([x[0] for x in np.array(y_train)]))
new_y_pred_RF_stacking = new_model_RF_stacking.predict(new_X_test_stacking)
new_y_pred_train_RF_stacking = new_model_RF_stacking.predict(new_X_train_stacking)

In [224]:
#Getting model results
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

accuracy = accuracy_score(y_test, new_y_pred_RF_stacking)
accuracy_train = accuracy_score(y_train, new_y_pred_train_RF_stacking)

precision = precision_score(y_test, new_y_pred_RF_stacking, average = "macro")
precision_train = precision_score(y_train, new_y_pred_train_RF_stacking, average = "macro")

recall = recall_score(y_test, new_y_pred_RF_stacking, average = "macro")
recall_train = recall_score(y_train, new_y_pred_train_RF_stacking, average = "macro")

f1 = f1_score(y_test, new_y_pred_RF_stacking, average = "macro")
f1_train = f1_score(y_train, new_y_pred_train_RF_stacking, average = "macro")

confusion = confusion_matrix(y_test, new_y_pred_RF_stacking)
confusion_train = confusion_matrix(y_train, new_y_pred_train_RF_stacking)

print("accuracy", accuracy)
print("accuracy_train", accuracy_train)
print("precision",precision)
print("precision_train",precision_train)
print("recall", recall)
print("recall_train", recall_train)
print("f1", f1)
print("f1_train", f1_train)
print("confusion", confusion)
print("confision_train", confusion_train)

accuracy 0.7915933044017359
accuracy_train 0.9000363995021488
precision 0.721445447430614
precision_train 0.8970176363148256
recall 0.7585451785270368
recall_train 0.8891666316120973
f1 0.7206318210331585
f1_train 0.8657890316610471
confusion [[28574  7630     9   728    50     9]
 [  966  3434     4   389  1264     5]
 [   15    49  2791   340   301     0]
 [  106   309   178  7542  2987    10]
 [   33   140    26   762  3118    10]
 [    9    39     2   349    89 18383]]
confision_train [[55575   420     1     4     0     0]
 [   33 16671     8    44  1427     1]
 [    0     0  8681    55  1755     0]
 [    1    29    44 20536 12779     4]
 [    0     4    20    84 12156     0]
 [    0     2     0    25   287 39686]]
